### ISSUE TITLE
Installation instructions on README

### ISSUE THREAD

**Issue by bfpc** [odow/SESO2023#2]
I was following the installation instructions (from inside VSCode) and when starting the IJulia notebook I got the following message:

>     julia> IJulia.notebook(dir = ".")
>     install Jupyter via Conda, y/n? [y]:
>     [ Info: Running `conda install -y jupyter` in root environment

The first time I pressed "y" and got an error (apparently a Zip file not being correct, which could have been a failed download, though I was on cable...).  I tried again, and it worked, so I can't reproduce.  Anyway, indicating that people will have to answer "y" there (or "just press Enter") should help.

**Comment by odow** [comment]
Is this on Windows?

**Comment by bfpc** [comment]
> Is this on Windows?

Yes.  I cloned the repository, opened VSCode, activated the project and followed the instructions.

**Comment by odow** [comment]
Hmm yeah I saw this with someone yesterday but it was on a locked-down industrial machine so I thought that was the problem.

**Comment by odow** [comment]
Any suggestions for https://github.com/odow/SESO2023/pull/3?

**Comment by bfpc** [comment]
> Hmm yeah I saw this with someone yesterday but it was on a locked-down industrial machine so I thought that was the problem.

It is possible.  I used the machine at the university, which is managed by the IT.  Curiously, "trying again" worked for the Zip file error.

As for #3, LGTM.

**Comment by odow** [comment]
Yeah seemed like the zip was just a spurious network issue that downloaded a corrupted file?
